# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.deploy.parameters]
stack_name = "sam-app"
cached = true
parallel = true
lint = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
s3_prefix = "sam-app"
region = "ap-southeast-1"
image_repositories = []
watch = true
warm_containers = "EAGER"
